# mypy.ini
[mypy]
python_version = 3.12
disable_error_code = no-redef
files = src
explicit_package_bases = True
mypy_path = src

[mypy-torchvision.*]
ignore_missing_imports = True
[mypy-torch.*]
ignore_missing_imports = True

[mypy-evidently.*]
ignore_missing_imports = True

[mypy-the_well.*]
ignore_missing_imports = True
[mypy-fsspec.*]
ignore_missing_imports = True
[mypy-einops.*]
ignore_missing_imports = True
